'use strict';

module.exports = {
    USERNAME_MIN_LENGTH: 1,
    USERNAME_MAX_LENGTH: 35,
    PHONE_MIN_LENGTH: 6,
    PHONE_MAX_LENGTH: 16,
    PASS_MIN_LENGTH: 6,
    PASS_MAX_LENGTH: 35,
    ORGANIZATION_MIN_LENGTH: 2,
    ORGANIZATION_MAX_LENGTH: 35,
    TITLE_MIN_LENGTH: 6,
    TITLE_MAX_LENGTH: 35,
    COMMENTS_MAX_LENGTH: 300

};